### ISSUE TITLE
Parser does not correctly convert to underscores in case where numbers are a word boundary

### ISSUE THREAD

**Issue by djackson-sykes** [django-json-api/rest_framework_ember#22]
Say we have a model with the following field:

    address_1 = models.CharField(max_length=255)

The Renderer will correctly transform that field to `address1`. If we send back an `address1` field in a POST/PUT, however, our model will fail to validate, complaining that `address_1` is missing.

This is due to a limitation of inflection, which does not consider numbers to be word boundaries when underscoring. I'm not sure whether that's an "issue" from the perspective of the inflection maintainers (presumably most users are fine with this behavior, since no one seems to be complaining about it). It does pose a problem for this library, however: field names that are perfectly acceptable to Django will result in obtuse errors in rest_framework_ember.

There's a few possible solutions -- we could wrap underscore() with some extra regex magic to find numbers, for instance. That would break field names like `5spooky3me = BooleanField()`, however, so it'd have to be a switch. If nothing else, it'd be worth a loud callout in the README, to steer users away from names like `address_1` in their models when using rest_framework_ember.

**Comment by jerel** [comment]
Thanks for reporting. I'd be happy to wrap the inflector to solve this as long as we're pretty certain that it won't break more fields than it fixes. I wonder if it would be prudent for us to open an issue on the inflector to see what input we could get from developers there? (IE why they don't support it)

**Comment by erichonkanen** [comment]
^^ interesting, I would def open a ticket with inflection repo first to see if an update can be made there...

**Comment by jerel** [comment]
@djackson-sykes @erichonkanen I opened a PR on the inflector and you can read the [author's comment over there](https://github.com/jpvanhal/inflection/pull/2). As it doesn't seem like theres a good automated solution I added a note to the README in b344a2ddf841246e5855c9f4d5af7eaa5f30a547. Using `address_one` seems to be the best solution to me. Thoughts?

**Comment by erichonkanen** [comment]
@jerel read that and it seems like indeed using the form "address_one" works fine, just needs documentation

**Comment by jerel** [comment]
Since I added a note to the README about this limitation I'm closing this issue.
