### ISSUE TITLE
Pagination tests failing

### ISSUE THREAD

**Issue by gaker** [django-json-api/rest_framework_ember#26]
See: https://travis-ci.org/django-json-api/rest_framework_ember/builds/53516979

**Comment by jerel** [comment]
Since this package tests against the latest DRF this is very likely caused by the DRF 3.1 release as it changed the pagination api http://www.django-rest-framework.org/topics/3.1-announcement/

**Comment by jerel** [comment]
Fixed by a41d9d5f6f93b866c9002e9953b870363f8323ff
