### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by nigelsmith** [django-json-api/rest_framework_ember#29]
Hi,

I ran into a python 3 issue with the use of basestring, but upon checking utils.py in master I see it's already fixed. Is there a plan to do a bug-fix release soon?

**Comment by jerel** [comment]
I am working on a bugfix release today

**Comment by jerel** [comment]
Full Python 3 support completed with 472d86e7b5a489498908a0e833835c9b36e62810

We just tagged v1.2.1 to fix Python 3 support. If you're running DRF 3.1.x then you'll want v1.3.0 as it adds updated pagination

**Comment by nigelsmith** [comment]
Many thanks @jerel
